name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define workflow-level environment variables
env:
  WORKFLOW_ENV_VAR: "This is a workflow-level environment variable"

jobs:
  build:
    runs-on: ubuntu-latest

    # Reference the environment
    environment: demo

    # Define job-level environment variables
    env:
      JOB_ENV_VAR: "This is a job-level environment variable"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run a dummy Maven command
        run: mvn --version  # This will not fail and will print the Maven version

      - name: Echo a secret
        run: echo "The secret value is ${{ secrets.MY_SECRET }}"

      - name: Echo workflow-level environment variable
        run: echo "$WORKFLOW_ENV_VAR"

      - name: Echo job-level environment variable
        run: echo "$JOB_ENV_VAR"

      - name: Define and use a step-level environment variable
        env:
          STEP_ENV_VAR: "This is a step-level environment variable"
        run: |
          echo "$STEP_ENV_VAR"

      - name: Use a GitHub Actions variable
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Run ID: $GITHUB_RUN_ID"

      - name: Echo Done
        run: echo "Done"